'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { SOUND_EFFECT_MAX_BYTES, type SoundEffect } from '@/lib/sound-effects';

const empty: SoundEffect = { id: 0, name: '', description: '', filePath: '', durationSeconds: 0, defaultVolumeDb: -18, syncPointSeconds: 0, tags: '', usageRules: '', sourceCredit: '', license: '', status: 'Draft' };
const inputClass = 'mt-1 w-full rounded-lg border border-slate-300 bg-white p-2 text-sm text-slate-900';
const buttonClass = 'rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium hover:bg-slate-100 disabled:opacity-50';
const duration = (seconds: number) => seconds >= 60 ? `${Math.floor(seconds / 60)}:${(seconds % 60).toFixed(3).padStart(6, '0')}` : `${seconds.toFixed(3)}s`;
const volume = (db: number) => Math.min(1, Math.max(0, 10 ** (db / 20)));

export default function SoundEffectsPage() {
  const [sounds, setSounds] = useState<SoundEffect[]>([]);
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false);
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [query, setQuery] = useState(''), [filter, setFilter] = useState('All');
  const [draft, setDraft] = useState<SoundEffect | null>(null), [original, setOriginal] = useState(''), [pendingFile, setPendingFile] = useState<File | null>(null);
  const pendingUrl = useMemo(() => pendingFile ? URL.createObjectURL(pendingFile) : '', [pendingFile]);
  useEffect(() => () => { if (pendingUrl) URL.revokeObjectURL(pendingUrl); }, [pendingUrl]);
  const dirty = !!draft && (JSON.stringify(draft) !== original || !!pendingFile);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const response = await fetch('/api/sound-effects'); const data = await response.json(); if (!response.ok) throw new Error(data.error); setSounds(data.sounds); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load library.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (!dirty) return; const handler = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ''; }; window.addEventListener('beforeunload', handler); return () => window.removeEventListener('beforeunload', handler); }, [dirty]);
  function open(sound: SoundEffect | null) { if (dirty && !window.confirm('Discard your unsaved changes?')) return; setDraft(sound); setOriginal(JSON.stringify(sound)); setPendingFile(null); setError(''); setNotice(''); }
  function update<K extends keyof SoundEffect>(key: K, value: SoundEffect[K]) { setDraft(current => current ? { ...current, [key]: value } : null); }
  async function save() { if (!draft) return; setBusy(true); setError(''); setNotice(''); try { const form = new FormData(); for (const [key, value] of Object.entries(draft)) form.set(key, String(value)); if (pendingFile) form.set('file', pendingFile); const response = await fetch('/api/sound-effects', { method: draft.id ? 'PATCH' : 'POST', body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setSounds(current => draft.id ? current.map(sound => sound.id === draft.id ? data.sound : sound) : [...current, data.sound]); setDraft(data.sound); setOriginal(JSON.stringify(data.sound)); setPendingFile(null); setNotice('Sound effect saved and measured.'); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save sound effect.'); } finally { setBusy(false); } }
  async function remove() { if (!draft?.id || !window.confirm(`Delete “${draft.name || 'Untitled sound'}” and its audio file?`)) return; setBusy(true); setError(''); try { const response = await fetch(`/api/sound-effects?id=${draft.id}`, { method: 'DELETE' }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setSounds(current => current.filter(sound => sound.id !== draft.id)); setDraft(null); setOriginal(''); setPendingFile(null); setNotice('Sound effect deleted.'); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to delete sound effect.'); } finally { setBusy(false); } }
  const visible = sounds.filter(sound => (filter === 'All' || sound.status === filter) && `${sound.name} ${sound.description} ${sound.tags}`.toLowerCase().includes(query.toLowerCase()));
  const audioSource = pendingUrl || draft?.filePath || '';
  return <main className='min-h-screen bg-slate-50 p-6 text-slate-900'><div className='mx-auto max-w-7xl space-y-6'>
    <header className='flex flex-wrap items-center justify-between gap-4'><div><Link href='/' onClick={event => { if (dirty && !window.confirm('Discard your unsaved changes?')) event.preventDefault(); }} className='text-sm text-blue-700'>← Video Editor</Link><h1 className='mt-3 text-3xl font-semibold'>Sound Effects Library</h1><p className='mt-1 text-slate-600'>Upload reusable sounds, preview them, and define how HyperFrames should use them.</p></div><button className={`${buttonClass} bg-blue-600 text-white hover:bg-blue-700`} disabled={busy} onClick={() => open({ ...empty })}>Add sound</button></header>
    {error && <div role='alert' className='rounded-lg bg-red-50 p-3 text-red-700'>{error}</div>}{notice && <p role='status' className='text-green-700'>{notice}</p>}
    <div className='flex flex-wrap gap-3'><input aria-label='Search sounds' placeholder='Search names, descriptions, or tags…' className={`${inputClass} mt-0 max-w-md`} value={query} onChange={event => setQuery(event.target.value)} /><select aria-label='Filter status' className='rounded-lg border p-2' value={filter} onChange={event => setFilter(event.target.value)}><option>All</option><option>Draft</option><option>Approved</option></select><button className={buttonClass} disabled={loading || busy} onClick={() => void load()}>Refresh</button></div>
    <div className={`grid gap-6 ${draft ? 'lg:grid-cols-2' : ''}`}><section aria-label='Sound effects' className='grid content-start gap-4 sm:grid-cols-2'>
      {loading ? <p>Loading library…</p> : visible.length === 0 ? <p>No matching sounds. Add an audio file to get started.</p> : visible.map(sound => <article key={sound.id} className={`rounded-xl border bg-white p-4 shadow-sm ${draft?.id === sound.id ? 'ring-2 ring-blue-500' : ''}`}><button disabled={busy} onClick={() => open({ ...sound })} className='w-full text-left'><div className='flex items-center justify-between gap-2'><h2 className='font-semibold'>{sound.name}</h2><span className={`rounded-full px-2 py-1 text-xs ${sound.status === 'Approved' ? 'bg-green-100 text-green-800' : 'bg-amber-100 text-amber-800'}`}>{sound.status}</span></div><p className='mt-2 line-clamp-2 text-sm text-slate-600'>{sound.description}</p><p className='mt-2 text-xs text-slate-500'>{duration(sound.durationSeconds)} · {sound.defaultVolumeDb.toFixed(1)} dB</p><p className='mt-1 text-xs text-slate-500'>{sound.tags}</p></button><audio className='mt-3 w-full' controls preload='none' src={sound.filePath} onPlay={event => { event.currentTarget.volume = volume(sound.defaultVolumeDb); }} /></article>)}
    </section>{draft && <section aria-label='Sound editor' className='space-y-4 rounded-xl border bg-white p-5 shadow-sm'><div className='flex items-center justify-between'><h2 className='text-xl font-semibold'>{draft.id ? 'Edit sound' : 'New sound'}{dirty ? ' • Unsaved' : ''}</h2><button disabled={busy} className={buttonClass} onClick={() => open(null)}>Close</button></div><fieldset disabled={busy} className='space-y-4'>
      <label className='block text-sm font-medium'>Name<input className={inputClass} value={draft.name} maxLength={200} onChange={event => update('name', event.target.value)} /></label><label className='block text-sm font-medium'>Description<textarea className={inputClass} value={draft.description} onChange={event => update('description', event.target.value)} /></label>
      <label className='block text-sm font-medium'>{draft.id ? 'Replace audio file' : 'Audio file'}<input type='file' accept='.wav,.mp3,.m4a,.aac,.flac,.ogg,.opus,.aiff,.aif,audio/*' className='mt-2 block text-sm' onChange={event => { const file = event.target.files?.[0] || null; event.target.value = ''; if (!file) return; if (file.size > SOUND_EFFECT_MAX_BYTES) { setError('Audio must be smaller than 25 MB.'); return; } setPendingFile(file); update('status', 'Draft'); setError(''); }} /></label>{pendingFile && <p className='text-xs text-amber-700'>Selected: {pendingFile.name}. Duration will be measured when saved, and status will return to Draft.</p>}{audioSource && <audio className='w-full' controls preload='metadata' src={audioSource} onPlay={event => { event.currentTarget.volume = volume(draft.defaultVolumeDb); }} />}<p className='text-xs text-slate-500'>Measured duration: {pendingFile ? 'measured after save' : duration(draft.durationSeconds)}</p>
      <label className='block text-sm font-medium'>Default volume: {draft.defaultVolumeDb.toFixed(1)} dB<input className='mt-2 w-full' type='range' min='-60' max='6' step='0.5' value={draft.defaultVolumeDb} onChange={event => update('defaultVolumeDb', Number(event.target.value))} /></label><label className='block text-sm font-medium'>Sync point (seconds)<input className={inputClass} type='number' min='0' max={draft.durationSeconds || undefined} step='0.001' value={draft.syncPointSeconds} onChange={event => update('syncPointSeconds', Number(event.target.value))} /></label><label className='block text-sm font-medium'>Tags<input className={inputClass} placeholder='click, transition, interface' value={draft.tags} onChange={event => update('tags', event.target.value)} /></label><label className='block text-sm font-medium'>Usage rules<textarea className={inputClass} placeholder='Use on confirmed UI clicks. Do not loop.' value={draft.usageRules} onChange={event => update('usageRules', event.target.value)} /></label><label className='block text-sm font-medium'>Source / credit<textarea className={inputClass} value={draft.sourceCredit} onChange={event => update('sourceCredit', event.target.value)} /></label><label className='block text-sm font-medium'>License<textarea className={inputClass} value={draft.license} onChange={event => update('license', event.target.value)} /></label><label className='block text-sm font-medium'>Status<select className={inputClass} value={draft.status} onChange={event => update('status', event.target.value as SoundEffect['status'])}><option>Draft</option><option>Approved</option></select></label>
    </fieldset><div className='flex flex-wrap gap-2'><button className={`${buttonClass} bg-blue-600 text-white hover:bg-blue-700`} disabled={busy || !draft.name.trim() || (!draft.filePath && !pendingFile)} onClick={() => void save()}>{busy ? 'Measuring and saving…' : 'Save sound'}</button>{!!draft.id && <button className={`${buttonClass} text-red-700`} disabled={busy} onClick={() => void remove()}>Delete</button>}</div></section>}</div>
  </div></main>;
}
