'use client';

import { useMemo } from 'react';
import { useAppStore } from '@/store/useAppStore';
import { RotateCcw, Subtitles } from 'lucide-react';
// fonts mapping generated by scripts/generate_ffmpeg_fonts.py
import ffmpegFonts from '../../docs/ffmpeg-fonts.json';

export default function SubtitleGenerationSettings() {
  const {
    subtitleGenerationSettings,
    updateSubtitleGenerationSettings,
    resetSubtitleGenerationSettings,
  } = useAppStore();

  const {
    enableCharLimit,
    maxChars,
    fontFamily,
    positionXPercent,
    positionYPercent,
    sizeHeightPercent,
  } = subtitleGenerationSettings;

  const availableFontFamilies = useMemo(() => {
    const mapping = ffmpegFonts as Record<string, string>;
    const keys = Object.keys(mapping || {}).filter(
      (k) => k && k !== 'user_fonts_dir',
    );
    keys.sort((a, b) => a.localeCompare(b));
    return keys.length ? keys : ['Lilita One', 'Helvetica', 'Arial'];
  }, []);

  return (
    <div className='bg-white rounded-lg border border-gray-200 p-4 shadow-sm hover:shadow-md transition-shadow duration-200'>
      <div className='flex items-start justify-between mb-3'>
        <div className='flex items-center gap-2'>
          <Subtitles className='w-5 h-5 text-yellow-600' />
          <div>
            <h3 className='font-semibold text-gray-900'>Subtitles</h3>
            <p className='text-xs text-gray-600'>
              Batch subtitle generation filters
            </p>
          </div>
        </div>
        <button
          onClick={resetSubtitleGenerationSettings}
          className='p-1.5 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-md transition-colors duration-200'
          title='Reset subtitle settings'
          type='button'
        >
          <RotateCcw className='w-3.5 h-3.5' />
        </button>
      </div>

      <div className='space-y-3'>
        <label className='flex items-start gap-3 cursor-pointer'>
          <input
            type='checkbox'
            checked={enableCharLimit}
            onChange={(e) =>
              updateSubtitleGenerationSettings({
                enableCharLimit: e.target.checked,
              })
            }
            className='mt-1 w-5 h-5 text-yellow-600 bg-white border-2 border-gray-300 rounded-md focus:ring-2 focus:ring-yellow-500 focus:border-yellow-500 transition-colors duration-200'
          />
          <div className='flex-1 min-w-0'>
            <div className='text-sm font-medium text-gray-900'>
              Only generate when transcription is shorter than a limit
            </div>
            <div className='text-xs text-gray-600'>
              Counts characters from the transcription text (including
              punctuation).
            </div>
          </div>
        </label>

        <div className='flex items-center gap-2'>
          <div className='text-xs text-gray-700 whitespace-nowrap'>
            Max chars:
          </div>
          <input
            type='number'
            min={1}
            step={1}
            value={Number.isFinite(maxChars) ? maxChars : 100}
            disabled={!enableCharLimit}
            onChange={(e) => {
              const raw = Number(e.target.value);
              updateSubtitleGenerationSettings({ maxChars: raw });
            }}
            className={`w-28 px-2 py-1 text-sm rounded-md border focus:outline-none focus:ring-2 transition-colors ${
              enableCharLimit
                ? 'border-gray-300 focus:ring-yellow-500 focus:border-yellow-500'
                : 'border-gray-200 bg-gray-50 text-gray-400'
            }`}
          />
          <div className='text-xs text-gray-500'>characters</div>
        </div>

        <div className='pt-3 mt-3 border-t border-gray-100' />

        <div className='space-y-2'>
          <div className='text-xs font-medium text-gray-700'>Style</div>

          <div className='grid grid-cols-2 gap-2'>
            <label className='space-y-1'>
              <div className='text-[11px] text-gray-600'>Font</div>
              <select
                value={fontFamily}
                onChange={(e) =>
                  updateSubtitleGenerationSettings({
                    fontFamily: e.target.value,
                  })
                }
                className='w-full px-2 py-1.5 text-sm rounded-md border border-gray-300 focus:outline-none focus:ring-2 focus:ring-yellow-500 focus:border-yellow-500'
              >
                {availableFontFamilies.map((f) => (
                  <option key={f} value={f}>
                    {f}
                  </option>
                ))}
              </select>
            </label>

            <label className='space-y-1'>
              <div className='text-[11px] text-gray-600'>Font size (%)</div>
              <input
                type='number'
                min={5}
                max={100}
                step={1}
                value={
                  Number.isFinite(sizeHeightPercent) ? sizeHeightPercent : 100
                }
                onChange={(e) =>
                  updateSubtitleGenerationSettings({
                    sizeHeightPercent: Number(e.target.value),
                  })
                }
                className='w-full px-2 py-1.5 text-sm rounded-md border border-gray-300 focus:outline-none focus:ring-2 focus:ring-yellow-500 focus:border-yellow-500'
              />
            </label>
          </div>

          <div className='grid grid-cols-2 gap-2'>
            <label className='space-y-1'>
              <div className='text-[11px] text-gray-600'>X (%)</div>
              <input
                type='number'
                min={0}
                max={100}
                step={1}
                value={
                  Number.isFinite(positionXPercent) ? positionXPercent : 50
                }
                onChange={(e) =>
                  updateSubtitleGenerationSettings({
                    positionXPercent: Number(e.target.value),
                  })
                }
                className='w-full px-2 py-1.5 text-sm rounded-md border border-gray-300 focus:outline-none focus:ring-2 focus:ring-yellow-500 focus:border-yellow-500'
              />
            </label>

            <label className='space-y-1'>
              <div className='text-[11px] text-gray-600'>Y (%)</div>
              <input
                type='number'
                min={0}
                max={100}
                step={1}
                value={
                  Number.isFinite(positionYPercent) ? positionYPercent : 50
                }
                onChange={(e) =>
                  updateSubtitleGenerationSettings({
                    positionYPercent: Number(e.target.value),
                  })
                }
                className='w-full px-2 py-1.5 text-sm rounded-md border border-gray-300 focus:outline-none focus:ring-2 focus:ring-yellow-500 focus:border-yellow-500'
              />
            </label>
          </div>

          <div className='text-[11px] text-gray-500 leading-relaxed'>
            X/Y are percentages of the video frame (0–100). Font size matches
            the server setting used for subtitle burn-in.
          </div>
        </div>

        <div className='text-[11px] text-gray-500 leading-relaxed'>
          Applies to:{' '}
          <span className='font-semibold'>
            Batch Operations → Subtitles → Generate All
          </span>
          .
        </div>
      </div>
    </div>
  );
}
